spring.application.name=swissroute

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/swissroute}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true

# ===============================
# API EXTERNA
# ===============================
swiss.api.base-url=${SWISS_API_BASE_URL:http://transport.opendata.ch/v1}

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=${JWT_SECRET:swissroute_jwt_secret_key_that_should_be_changed_in_production}
jwt.expiration=${JWT_EXPIRATION:86400}
